version: '3'
services:
  web:
    container_name: movies-web
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/usr/app
    command: yarn start
  db:
    container_name: movies-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db